version: "2"

services:
  odoo:
    build: .
    image: img_odoo_10
    container_name: odoo_v10
    depends_on:
      - db
    volumes:
      - "data-odoo-10:/filestore"
      - "./custom-addons/:/opt/custom-addons"
      - "./src:/opt/odoo"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=odoo
    ports:
      - "8010:8069"
      - "8072:8069"
    restart: always
    command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    networks:
      - red-odoo10-db

  db:
    image: postgres:9.6
    container_name: postgres_v9.6
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db-10:/var/lib/postgresql/data"
    ports:
      - "5410:5432"
    restart: always
    networks:
      - red-odoo10-db

networks:
  red-odoo10-db:

volumes:
  data-odoo-10:
  data-db-10:
